image: maven:3-jdk-8

stages:
  - test
  - deploy

tests:
  stage: test
  script:
    - /bin/sh -c "mvn -U --batch-mode clean verify sonar:sonar -Pcoverage-per-test -Dsonar.host.url=https://sonar.arxes-tolina.de -Dsonar.issuesReport.console.enable=true -Dsonar.gitlab.commit_sha=$CI_BUILD_REF -Dsonar.gitlab.ref=$CI_BUILD_REF_NAME -Dsonar.gitlab.url=https://gitlab.arxes-tolina.de -Dsonar.gitlab.project_id=ron.peters/annotation-validator"
  tags:
    - docker

variables:
  BUILD_ENV: "DOCKER"
